#ifndef IMAGEPROCESSLIB_GLOBAL_H
#define IMAGEPROCESSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEPROCESSLIB_LIBRARY)
#  define IMAGEPROCESSLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEPROCESSLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPROCESSLIB_GLOBAL_H
